let log4js = require('log4js');
let fs = require('fs');
let path = require('path');
let directory = './.reports/json-output-folder';
let fileUtil = require("./utility/fileUtil.js")

exports.config = {
    directConnect: true,
    // seleniumAddress: 'http://localhost:4444/wd/hub/',
    SELENIUM_PROMISE_MANAGER: false,
    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    specs: ['./features/*.feature'],
    setPageTimeout: 100000,
    setDefaultTimeout: 60 * 1000,
    capabilities: {
        browserName: 'chrome'
    },

    // --------------------------Multi browser Parallel Execution Chrome and Safari-------------------
    /* multiCapabilities: [
         {
             'browserName': 'chrome',
             'chromeOptions': {
                 'args': ['show-fps-counter=true'],
                 //'args': [ "--headless", "--disable-gpu", "--window-size=800,600" ]
             }
         },
         {
             'browserName': 'safari',
             'moz:firefoxOptions': {
                'args': ['--safe-mode'],
                //'args': [ "--headless" ]
            }
        }
    ],
    */

    cucumberOpts: {
        require: ['./stepDefinations/*.js', './hooks/*.js'],
        format: 'json:.reports/results.json',
        strict: true,
        tags: '@customerLogin'
    },

    beforeLaunch: function () {
        if (fs.existsSync('./logs/site.log')) {
            fs.unlinkSync('./logs/site.log')
        }
        if (fs.existsSync(directory)) {
            fs.readdir(directory, (err, files) => {
                if (err) throw err;

                for (const file of files) {
                    fs.unlink(path.join(directory, file), err => {
                        if (err) throw err;
                    });
                }
            })
        };
        log4js.configure({
            appenders: {
                out: {
                    type: 'console'
                },
                app: {
                    type: 'file',
                    filename: 'logs/site.log'
                }
            },
            categories: {
                default: {
                    appenders: ['out', 'app'],
                    level: 'debug'
                }
            }
        });
    },

    onPrepare: function () {
        browser.logger = log4js.getLogger('protractorLog4js');
        browser.manage().window().maximize();
    },

    onComplete: function () {
        fileUtil.archiveReport('.reports/report/index.html')

    },

    plugins: [{
        package: require.resolve('protractor-multiple-cucumber-html-reporter-plugin'),
        options: {
            automaticallyGenerateReport: true,
            removeExistingJsonReportFile: true,
            openReportInBrowser: true,
            pageTitle: "NAGP Protractor Assignment Report",
            pageFooter: "<div><p>test report generated by Arjit Kathuria</p></div>",
            customData: {
                title: 'Protractor Assignment Report',
                data: [{
                        label: 'Project',
                        value: 'NAGP'
                    },
                    {
                        label: 'Created By',
                        value: 'Arjit Kathuria'
                    }
                ]
            }
        },

    }]
}